[versions]
# Project
namespace = "com.alorma.fireandforget"

# Android Gradle Plugin
agp = "8.13.2"

# Android SDK
android-minSdk = "21"
android-minSdkSample = "34"
android-compileSdk = "36"
android-targetSdk = "36"

# Publishing
mavenPlugin = "0.35.0"

androidx-activity = "1.12.2"
composeMultiplatform = "1.9.3"
kotlin = "2.3.0"
multiplatform-settings = "1.3.0"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "composeMultiplatform" }

plugin-gradle-maven-publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "mavenPlugin" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

multiplatform-settings = { group = "com.russhwolf", name = "multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-no-arg = { group = "com.russhwolf", name = "multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinMultiplatformAndroidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }